spring:
   datasource:
      url: jdbc:mysql://localhost:3306/parkinson
      username: root
      password: root
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
      hibernate:
         ddl-auto: create-drop
server:
   port: 8080
   
---

spring:
   profiles: container
   datasource:
      url: jdbc:mysql://localhost:3306/parkinson
      username: root
      password: root
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
      hibernate:
         ddl-auto: create-drop
server:
   port: 8080